######################################################################
#
# File name : tb_clahe_top_bmp_multi_compile.do
# Created on: Tue Dec 02 23:56:05 +0800 2025
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vlog -64 -incr -work xil_defaultlib  \
"tb_clahe_top_bmp_multi_func_synth.v" \

E:\\modeltech64_2020.4\\win64\\vlog -64 -incr -sv -work xil_defaultlib  \
"../../../../../clahe_vivado.srcs/sim_1/imports/tb/bmp_for_videoStream_24bit.sv" \
"../../../../../clahe_vivado.srcs/sim_1/imports/tb/bmp_to_videoStream.sv" \
"../../../../../clahe_vivado.srcs/sim_1/imports/tb/tb_clahe_top_bmp_multi.sv" \

quit -force

