######################################################################
#
# File name : tb_clahe_top_bmp_multi_wave.do
# Created on: Wed Dec 03 00:05:05 +0800 2025
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
