######################################################################
#
# File name : tb_clahe_top_bmp_multi_wave.do
# Created on: Tue Dec 02 20:22:16 +0800 2025
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
