######################################################################
#
# File name : tb_clahe_top_bmp_multi_simulate.do
# Created on: Wed Dec 03 00:05:05 +0800 2025
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_clahe_top_bmp_multi xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_clahe_top_bmp_multi_wave.do}

view wave
view structure
view signals

do {tb_clahe_top_bmp_multi.udo}

run 1000ns
