######################################################################
#
# File name : tb_clahe_top_bmp_multi_compile.do
# Created on: Sun Dec 07 16:36:19 +0800 2025
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vlog -64 -incr -work xil_defaultlib  \
"tb_clahe_top_bmp_multi_func_synth.v" \

E:\\modeltech64_2020.4\\win64\\vlog -64 -incr -sv -work xil_defaultlib  \
"../../../../../../../projects/64tile/tb/bmp_for_videoStream_24bit.sv" \
"../../../../../../../projects/16tile/tb/bmp_to_videoStream.sv" \
"../../../../../../../projects/64tile/tb/tb_clahe_top_bmp_multi.sv" \

quit -force

