######################################################################
#
# File name : tb_clahe_top_bmp_multi_compile.do
# Created on: Tue Dec 02 23:37:59 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../clahe_vivado.srcs/sources_1/imports/rtl/clahe_clipper_cdf.v" \
"../../../../clahe_vivado.srcs/sources_1/imports/rtl/clahe_coord_counter.v" \
"../../../../clahe_vivado.srcs/sources_1/imports/rtl/clahe_histogram_stat.v" \
"../../../../clahe_vivado.srcs/sources_1/imports/rtl/clahe_mapping_parallel.v" \
"../../../../clahe_vivado.srcs/sources_1/imports/rtl/clahe_ram_16tiles_parallel.v" \
"../../../../clahe_vivado.srcs/sources_1/imports/rtl/clahe_simple_dual_ram_model.v" \
"../../../../clahe_vivado.srcs/sources_1/imports/rtl/clahe_top.v" \
"../../../../clahe_vivado.srcs/sources_1/imports/rtl/clahe_true_dual_port_ram.v" \

E:\\modeltech64_2020.4\\win64\\vlog -64 -incr -sv -work xil_defaultlib  \
"../../../../clahe_vivado.srcs/sim_1/imports/tb/bmp_for_videoStream_24bit.sv" \
"../../../../clahe_vivado.srcs/sim_1/imports/tb/bmp_to_videoStream.sv" \
"../../../../clahe_vivado.srcs/sim_1/imports/tb/tb_clahe_top_bmp_multi.sv" \

# compile glbl module
E:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

