# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath E:/modeltech64_2020.4/win64
create_project -in_memory -part xc7z020clg400-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.cache/wt [current_project]
set_property parent.project_path E:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.srcs/sources_1/imports/rtl/clahe_clipper_cdf.v
  E:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.srcs/sources_1/imports/rtl/clahe_coord_counter.v
  E:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.srcs/sources_1/imports/rtl/clahe_histogram_stat.v
  E:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.srcs/sources_1/imports/rtl/clahe_mapping_parallel.v
  E:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.srcs/sources_1/imports/rtl/clahe_ram_16tiles_parallel.v
  E:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.srcs/sources_1/imports/rtl/clahe_simple_dual_ram_model.v
  E:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.srcs/sources_1/imports/rtl/clahe_true_dual_port_ram.v
  E:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.srcs/sources_1/imports/rtl/clahe_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.srcs/constrs_1/imports/clahe_top_sim.xdc
set_property used_in_implementation false [get_files E:/FPGA_codes/CLAHE/vivado_project/clahe_vivado/clahe_vivado.srcs/constrs_1/imports/clahe_top_sim.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top clahe_top -part xc7z020clg400-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef clahe_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file clahe_top_utilization_synth.rpt -pb clahe_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
